# Generated by Django 2.1.3 on 2018-12-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20181206_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='测试名称', max_length=50)),
                ('status', models.CharField(choices=[('normal', '正常'), ('hidden', '隐藏')], help_text='测试状态,normal:正常，hidden:隐藏', max_length=20)),
            ],
        ),
    ]
